GET http://localhost:3001/students

###

POST http://localhost:3001/student/new
Content-Type: application/json 

{
  "firstname":"asdfa",
  "lastname":"Asdf",
  "email":"asd@daf.com",
  "password": "Dadsa"
}

###

POST http://localhost:3001/student/new
Content-Type: application/json 

{
  "firstname":"123123123",
  "lastname":"Asdasdff",
  "email":"asd@daf.com",
  "password": "Dadsaasdfad"
}

###

POST http://localhost:3001/exam/create
Content-Type: application/json 

{
  "name": "math",
  "title": "math",
}

### 
POST http://localhost:3001/account
Content-Type: application/json 

      {
        "plan":"basic",
        "price":59,
        "term": "month"
      }